config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#show'

  # Dashboard
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # Session 
  get 'session/new', as: 'sign_in'
  delete 'session',  to: 'session#destroy', as: 'sign_out'
  get '/auth/github/callback', to: 'session#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, :email, :name, presence: true
  validates :uid, uniqueness: true
end

app/models/user/authenticable.rb
class User::Authenticable < ActiveType::Record[User]
  def self.authenticate(authorize_params)
    user = find_by(uid: authorize_params.fetch('uid'))
    
    if user.present?
      user
    else
      create!(
        uid: authorize_params.fetch('uid'),
        email: authorize_params.fetch('info').fetch('email'),
        name: authorize_params.fetch('info').fetch('nickname')
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :current_user, only: %i[show repositories]

  def show
    @repos = GithubApiService.new(@user).execute(dashboard_params.to_h)
    respond_to do |format|
      format.js
      format.html 
    end
  end

  def current_user
    @user = User.find_by!(uid: session[:uid])
    rescue ActiveRecord::RecordNotFound => errors
      render notice: {errors: errors}
  end

  def dashboard_params
    params.permit(:date, :language)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    # This route is catched by the Omniauth Middleware and is invisible to rake routes
    redirect_to '/auth/github'
  end

  def create
    user = User::Authenticable.authenticate(authorize_params)
    session[:uid] = user.uid
    redirect_to root_path
  end

  def destroy
    session.delete(:uid)
    redirect_to root_path
  end

  private

  def authorize_params
    request.env.fetch('omniauth.auth')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def signed_in?
    session[:uid].present?
  end

  def current_user
    User.find_by!(uid: session[:uid]) if signed_in?
  end
end

app/views/dashboard/_listing.html.erb
<h1 class="dashboard-heading"><%= title %></h1><br/>
<ul class="list-group dashboard-body">
  <% repos.each do |repo| %>
    <li class="list-group-item"><%= repo["name"] %><li/>
  <%end%>
</ul>

app/views/dashboard/show.html.erb
<br/>
<% if signed_in? %>
  <% # Filter %>
  <%= select_tag "filter", options_for_select(
    [['Week', (Date.today - 7.days).strftime('%Y-%m-%d')],
    ['Month', (Date.today - 1.month).strftime('%Y-%m-%d')],
    ['Year', (Date.today - 1.year).strftime('%Y-%m-%d')]]),
    include_blank: 'Please select',
    class: " btn btn-default filter-date" %>
  
  <%= check_box_tag 'language', '', false, class: 'filter-language' %> Ruby
  <button class="btn btn-primary filter-button">Filter</button>
  <br/><br/>

<% # Most popular repository %>
  <div id="display_listing">
    <%= render partial: 'dashboard/listing', locals: { repos: @repos, title: 'Your Repositories' } %>
  </div>
<% end %>

app/views/dashboard/show.js.erb
var content ="<%= j render partial: 'dashboard/listing', locals: { repos: @repos, title: 'Most Popular Repositories' } %>"
$('#display_listing').html(content)

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">GitHub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Dashboard</a>
      </li>
      <li class="nav-item">
        <% if signed_in? %>
          <%= link_to "Sign out #{current_user.name}", sign_out_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render partial: 'layouts/header' %>
  </header>
  
  <body>
    <%= yield %>
  </body>
</html>